### ISSUE TITLE
Undefined variables and function

### ISSUE THREAD

**Issue by tcoulvert** [quantummind/qaml-z#1]
Hi, I'm trying to run this code on the new DWave Advantage system, but I don't believe the code could run as-is. Specifically, there are some variables (and one function) that are referenced without ever being declared nor defined. 

Below are the links to the lines of code that contain undeclared/undefined variables:
- "POS_WEIGHTS" : https://github.com/quantummind/qaml-z/blob/2464e9c2396973511676afcf2db99831f63d9111/quantum-annealing.py#L37
- "POS_NEG_WEIGHTS" : https://github.com/quantummind/qaml-z/blob/2464e9c2396973511676afcf2db99831f63d9111/quantum-annealing.py#L39
- "full_strings" : https://github.com/quantummind/qaml-z/blob/2464e9c2396973511676afcf2db99831f63d9111/quantum-annealing.py#L180
- "try_number" : https://github.com/quantummind/qaml-z/blob/2464e9c2396973511676afcf2db99831f63d9111/quantum-annealing.py#L343

Below is the link to the line of code that contains the undeclared/undefined function:
- "hamiltonian_orig_posweights" : https://github.com/quantummind/qaml-z/blob/2464e9c2396973511676afcf2db99831f63d9111/quantum-annealing.py#L38

Is there another version of this code that has these variables and function defined? Or if not, how was it run originally and what steps should I take to replicate that?

**Comment by quantummind** [comment]
Removed unnecessary code (`hamiltonian_checker` and its references to `POS_WEIGHTS`, `POS_NEG_WEIGHTS`, `hamiltonian_orig_posweights`, `hamiltonian_orig_posnegweights`), removed saving directory (`'./mus' + str(try_number)`), and added `full_strings` definition.
