### ISSUE TITLE
Deprecated SAPI Packages, Need to Port to Ocean SDK

### ISSUE THREAD

**Issue by tcoulvert** [quantummind/qaml-z#2]
Hi, I'm trying to run this program on the DWave Advantage system. DWave deprecated their old SAPI packages at the end of 2019, so in order to run the code (even on the original 2000Q system) it needs to be ported to DWave's Ocean SDK. In fact, DWave doesn't even have the documentation for their old packages.

Do you happen to have a copy of the old documentation? It would really help expedite my analysis of the code and the porting process as a whole.

**Comment by jmduarte** [comment]
In particular, I think we want to understand the difference in output for the old `embed_problem` vs. new `embed_ising` here: 
https://github.com/dwavesystems/legacy-sapi-clients#embed-problem

@vlimant @quantummind if you remember / have the old docs

**Comment by quantummind** [comment]
The function `dwave_sapi2.embedding.embed_problem` returns:
* `h0`: embedded linear Ising coefficients
* `j0`: embedded quadratic Ising coefficients
* `jc`: strong output variable couplings
* `embeddings`: possibly modified embeddings

The new `embed_ising` returns only `h0` and `j0`.
