### ISSUE TITLE
One Last Undeclared Var

### ISSUE THREAD

**Issue by tcoulvert** [quantummind/qaml-z#3]
Hey, there's one more variable that wasn't declared only referenced, located here: 

https://github.com/quantummind/qaml-z/blob/0e79bc18e160a53deaac91e927b0a35d9c15ccc5/quantum-annealing.py#L244

POS_NEG_WEIGHTS is likely not crucial overall, but it is crucial for the functionality of the "ensemble" function, which is in turn called as one of the final steps in order to determine the final accuracy. Can I just delete the POS_NEG_WEIGHTS var? And if so how should I modify the "ensemble" method to maintain its functionality?

**Comment by quantummind** [comment]
`POS_NEG_WEIGHTS` was a flag set to `True`; code is fixed now!
